Adição de flags e pilha ao simulador
BenhurUFSM/so22b pull request #1
Opened 2022-09-29 15:04 UTC by crazynds

Sugestão para modificação do simulador para facilitar a implementação de código de máquina para alguns algoritmos.

Modificações feitas nesse pull request:
- Feito a refatoração do enum de opcodes para que seja centralizado em um arquivo independente, dessa forma ao adicionar um comando com um valor de opcode, tanto o montador quanto o executor vão ter a mesma referencia e vão executar corretamente.
- Adicionado no estado da cpu flags. Basicamente isso possibilita definir estados binários na cpu e consulta-las se está ativou ou não determinado estado. Essa flag é usada por essa branch principalmente para armazenar o estado da ultima comparação. Mais detalhes abaixo.
- Adicionado comando CMPA, que faz uma comparação de A com [A1] e altera as flags de acordo. Segue a [instrução real](https://www.felixcloutier.com/x86/cmp) que usei como referencia e adaptei para a estrutura de cpu do professor.
- Adicionado comando DESVA (Desviso se A é maior), DESVB (Desvio se B é maior), DESVE (Desvio se é igual) no conjunto de instruções. Facilitando fazer comparações, é possivel também adicionar os comandos DESVAE (Desvio se A é maior ou igual a B), DESVBE (Desvio se B é maior ou igual a A) utilizando as mesmas flags, porém para deixar simples o conjunto de instruções nesse pull request foi adicionado só os 3 anteriormente citados.  

Fiz alguns testes da utilização dos comandos, e da fatoração e está dando as saidas corretas, porém novos testes são sempre bem vindos.

2022-09-29 17:26 UTC, crazynds commented
Resumo dos ultimos 2 commits que foram feitos dps do pull request:
- Adicionado registrador de stack ao processador, junto a uma memória heap que é alocada no momento de alocação da memória para o código. 
- Adicionado comandos de push e pop.

2022-09-29 17:28 UTC, crazynds commented
Convertido para draft pois ainda não fiz todos os testes necessários e a implementação de todos os comandos.

2022-09-29 17:57 UTC, crazynds commented
Feito correções necessárias na pilha e adicionados mais os comandos PUSHX (Manda X para a pilha) e POPX (Pega o primeiro item da pilha e manda para X).

2022-09-29 17:58 UTC, crazynds commented
Modificações prontas.
Acredito que com a implementação da pilha já permite depois fazer o sistemas de call e interrupções mais fácil.

2022-09-30 20:18 UTC, BenhurUFSM approved these changes

2022-09-30 20:25 UTC, BenhurUFSM requested changes
OK, mas sem as instruções novas. Vou fazer um "t0b" com acréscimos.

2022-09-30 20:29 UTC, BenhurUFSM commented
Eu pensei ter aprovado só um dos commits, mas parece que o github
considerou o request inteiro...

On Thu, Sep 29, 2022 at 12:04 PM Crazynds ***@***.***> wrote:

> Modificações:
>
>    - Feito a refatoração do enum de opcodes para que seja centralizado em
>    um arquivo independente, dessa forma ao adicionar um comando com um valor
>    de opcode, tanto o montador quanto o executor vão ter a mesma referencia e
>    vão executar corretamente.
>    - Adicionado no estado da cpu flags. Basicamente isso possibilita
>    definir estados binários na cpu e consulta-las se está ativou ou não
>    determinado estado. Essa flag é usada por essa branch principalmente para
>    armazenar o estado da ultima comparação. Mais detalhes abaixo.
>    - Adicionado comando CMPA, que faz uma comparação de A com [A1] e
>    altera as flags de acordo. Segue a instrução real
>    <https://www.felixcloutier.com/x86/cmp> que usei como referencia e
>    adaptei para a estrutura de cpu do professor.
>    - Adicionado comando DESVA (Desviso se A é maior), DESVB (Desvio se B
>    é maior), DESVE (Desvio se é igual) no conjunto de instruções. Facilitando
>    fazer comparações, é possivel também adicionar os comandos DESVAE (Desvio
>    se A é maior ou igual a B), DESVBE (Desvio se B é maior ou igual a A)
>    utilizando as mesmas flags, porém para deixar simples o conjunto de
>    instruções nesse pull request foi adicionado só os 3 anteriormente citados.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/BenhurUFSM/so22b/pull/1
> Commit Summary
>
>    - f0066e4
>    <https://github.com/BenhurUFSM/so22b/pull/1/commits/f0066e4698208444487de695deeb1cf99faec9d1>
>    refactor: separado os dados de opcode comum em um arquivo externo
>    - 3678c52
>    <https://github.com/BenhurUFSM/so22b/pull/1/commits/3678c526572acb337f65b38994cd49938088f147>
>    feat: adicionado gitignore para evitar enviar arquivos compilados para o git
>    - 0951969
>    <https://github.com/BenhurUFSM/so22b/pull/1/commits/09519694bb76f87a45b4dd988fb4da1a8b73309d>
>    feat: adicionado suporte a flags na cpu
>    - 4f8a1a9
>    <https://github.com/BenhurUFSM/so22b/pull/1/commits/4f8a1a90666395e9a2d4d3b23ebe4526783d85b4>
>    feat: implementado no executor a lógica dos comandos de flags
>    - 5c97e2c
>    <https://github.com/BenhurUFSM/so22b/pull/1/commits/5c97e2c5bc4c60d52eef897914150ec01a37bcae>
>    fix: correcoes de código para funcionar corretamente o montador e as novas
>    instruções
>
> File Changes
>
> (9 files <https://github.com/BenhurUFSM/so22b/pull/1/files>)
>
>    - *A* t0/.gitignore
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-2e56fd594ae686d62ec193d5608a42618ecba00c1fedfd3fa894221090e31916>
>    (4)
>    - *M* t0/README.md
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-5fc428224b25503fce72f2d737d5f0a7f1e7140268211881baec28664868f32a>
>    (5)
>    - *M* t0/cpu_estado.c
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-961a942ba618e0182e835084f8a0de2b023c481f9a6d5d1f98dd0fc7005036d8>
>    (26)
>    - *M* t0/cpu_estado.h
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-131fa8954f918d6fdcaf01c8d967e4254353da66a7dab881da2a91466b747c6b>
>    (6)
>    - *M* t0/ex2.asm
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-780d621e68654aa7568e56ce0177bf58bd51b2f30215f448a278b0ba7c4d225c>
>    (9)
>    - *M* t0/exec.c
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-94b78c1b5a2faa056b708bdca1227edbd1b71e67fdb19e5993a002ba40f11ff3>
>    (40)
>    - *M* t0/exec.h
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-008160bf5952061a788a6e4ff7fcea0137ab6c9c40c54b1f7c9dace3fb7d6224>
>    (24)
>    - *M* t0/montador.c
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-c5e4530d18a5fb9397cdabbc5a8b891420efe284688e1e3ad5e6e09882e29a8c>
>    (71)
>    - *A* t0/opcode.h
>    <https://github.com/BenhurUFSM/so22b/pull/1/files#diff-3c4ee55c9b1c07ea997ba9460ffe69b71859eb88ceb6fb9cc5c23a998df8764a>
>    (39)
>
> Patch Links:
>
>    - https://github.com/BenhurUFSM/so22b/pull/1.patch
>    - https://github.com/BenhurUFSM/so22b/pull/1.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BenhurUFSM/so22b/pull/1>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUCNFYQ3R3Q356Q6BZTRK73WAWVYRANCNFSM6AAAAAAQY32HR4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-10-01 18:58 UTC, crazynds commented
Vou fechar o pull request, mas ai tu adiciona diretamente ao código o que achou interessante.

2022-10-01 18:58 UTC, closed without merging

2022-10-01 22:59 UTC, BenhurUFSM commented
OK.
Eu tava fazendo isso, mas tive uns probleminhas com meu computador, vou ver
se consigo amanhã.

On Sat, Oct 1, 2022 at 3:59 PM Crazynds ***@***.***> wrote:

> Vou fechar o pull request, mas ai tu adiciona diretamente ao código o que
> achou interessante.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BenhurUFSM/so22b/pull/1#issuecomment-1264452234>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUCNFYQJ6JBBUFKAAVFN2N3WBCCXTANCNFSM6AAAAAAQY32HR4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>